-- Магазин «Сулайман-Тоо» — журнал изменений audit_log
-- Нужен для раздела «🛠️ Правка рассрочек» (и уже используется в «💵 Касса»).
-- Скрипт безопасен для повторного запуска: если таблица уже есть, он только
-- добавит недостающие колонки и индекс. Данные не удаляет и не меняет.
--
-- Как выполнить: Supabase → проект → SQL Editor → New query → вставить весь файл → Run.

create table if not exists public.audit_log (
    id          bigint generated by default as identity primary key,
    created_at  timestamptz not null default now(),
    user_name   text,
    action      text,
    table_name  text,
    record_id   text,
    old_data    jsonb,
    new_data    jsonb,
    comment     text
);

alter table public.audit_log add column if not exists created_at timestamptz not null default now();
alter table public.audit_log add column if not exists user_name  text;
alter table public.audit_log add column if not exists action     text;
alter table public.audit_log add column if not exists table_name text;
alter table public.audit_log add column if not exists record_id  text;
alter table public.audit_log add column if not exists old_data   jsonb;
alter table public.audit_log add column if not exists new_data   jsonb;
alter table public.audit_log add column if not exists comment    text;

create index if not exists audit_log_table_created_idx on public.audit_log (table_name, created_at desc);

-- Как и остальные таблицы: RLS включён, политик нет. Приложение ходит ключом service_role
-- (SUPABASE_KEY в Streamlit Secrets), поэтому для него ничего не меняется,
-- а публичный anon-ключ к журналу доступа не получит.
-- ВНИМАНИЕ: если в Secrets всё ещё anon-ключ, сначала замените его на service_role,
-- иначе после этой строки приложение не сможет писать в журнал.
alter table public.audit_log enable row level security;
